### ISSUE TITLE
Unknown license found

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#101]
We have the following behavior in the license display:
![Captura de tela de 2023-02-23 16-24-30](https://user-images.githubusercontent.com/35712014/221009943-bd556d2e-fa3a-412d-b131-343683ac7d4d.png)

I replaced the previous LICENSE file by the GitHub-provided, but GH still seeks both: 
![Captura de tela de 2023-02-23 16-27-45](https://user-images.githubusercontent.com/35712014/221010332-f843346b-c385-4c28-bb64-8a633cc1c23f.png)

Any tips ? @TarikKaanKoc @snitramodranoel

**Comment by Joao-L-S-Almeida** [comment]
As you can see, the file LICENSE.md is inexistent.

**Comment by TarikKaanKoc** [comment]
Hi there @Joao-L-S-Almeida,

Based on your comment, it seems that GitHub is looking for a "LICENSE.md" file to identify the license for the project, even though there is no such file in the repository. In order to resolve this issue, you should make sure that a file named "LICENSE" is present in the repository, as GitHub expects to find the license information in a file with that name.

Best regards,

**Comment by TarikKaanKoc** [comment]
I have created a new license for this project and have removed the old license. The new license is now the official license for this project and it applies to all contributions going forward.
