### ISSUE TITLE
Should the directory utilities be in src/simulai ?

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#31]
Maybe it could be just another auxiliary directory placed on root simulai.

**Comment by TarikKaanKoc** [comment]
After considering the organization of the project, I suggest that the directory utilities should be placed in the `src/simulai` directory. This will keep similar files and functionality grouped together, making it easier to maintain and understand the project structure.

**Comment by TarikKaanKoc** [comment]
Another option to consider would be to place the directory utilities in another auxiliary directory at the root level of simulai, rather than within the `src/simulai` directory. This could make it more accessible for other parts of the project to use if the utilities are more general. Ultimately, the decision should be based on maintaining a clear and logical file structure for the project.

**Comment by Joao-L-S-Almeida** [comment]
I agree. As simulai/src/simulai/utilities just contains a set of benchmark tests and auxiliary scripts, it could be placed in simulai/, at the same level of src/. I will move it.
