### ISSUE TITLE
Some variables, as energy and concentration need to preserve positivity otherwise they became physically inconsistent. When these variables are represented via Autoencoders and PCA the way for enforcing positivity is the hard positivity limiting. It already works for PCA, but it still needs to be tested with NN Autoencoders.

### ISSUE THREAD

**Issue by Joao-L-S-Almeida** [IBM/simulai#93]

**Comment by TarikKaanKoc** [comment]
Hi @Joao-L-S-Almeida, 

It is important to ensure that certain variables such as energy and concentration remain positive when using Autoencoders and PCA, as they can become physically inconsistent otherwise. Your suggestion of using hard positivity limiting as a way to enforce this is a good one.

To address your request to test the hard positivity limiting method with NN Autoencoders, we agree that this would be a valuable addition to the project. However, it would be best if you could provide more details on how you plan to implement this and any specific help you might need. This way, we can ensure that the implementation meets the requirements of the project and does not conflict with existing features.
